#!/usr/bin/env python3
"""Coverage gate for the rebuild-from-zero tutorial.

Maps EVERY tracked file to the lesson that builds it (or an explicit
non-lesson bucket) and regenerates COVERAGE.md. Exits 1 if any file is
unmapped — the course's own arch test: an unmapped file is a hole in the
tutorial, not an oversight to shrug at.

Run from the repo root:  python docs/tutorial/gen_coverage.py
"""
from __future__ import annotations

import subprocess
import sys
from fnmatch import fnmatch
from pathlib import Path

# ---------------------------------------------------------------------------
# Lesson titles (must stay in sync with OUTLINE.md)
# ---------------------------------------------------------------------------
LESSONS: dict[str, str] = {
    "0.1": "Mental model & the decision record",
    "0.2": "A reproducible machine",
    "1.1": "Solution, projects & supply chain",
    "1.2": "First endpoint, first test",
    "1.3": "Database & the test container",
    "1.4": "Configuration & the options pattern",
    "1.5": "The error envelope",
    "1.6": "CI from commit one",
    "2.1": "Users & JWT access tokens",
    "2.2": "Rotating refresh tokens & sessions",
    "2.3": "Email I — the IEmailSender seam",
    "2.4": "Passwordless: magic link + OTP",
    "2.5": "OAuth & account linking",
    "2.6": "Tenancy I — the global query filter (reads)",
    "2.7": "Tenancy II — write-side stamping & EnterTenant",
    "2.8": "Tenants & membership",
    "2.9": "Invitations, dissolve & the contributor seam",
    "3.1": "The repository seam",
    "3.2": "Anatomy of a vertical slice (Notes)",
    "3.3": "Injected clocks & the architecture tests",
    "3.4": "The web client & auth UI",
    "3.5": "Localization (EN/ES)",
    "3.6": "The E2E harness (Playwright)",
    "3.7": "Build your own slice (capstone)",
    "4.1": "The transactional outbox",
    "4.2": "Email II — the outbox decorator",
    "4.3": "The inbox (idempotency)",
    "4.4": "The scheduler",
    "4.5": "Observability: logs, traces, health",
    "4.6": "The append-only audit log",
    "5.1": "Billing abstraction & entitlements",
    "5.2": "Stripe: checkout, webhook, portal",
    "5.3": "Quotas, dunning & billing dissolve",
    "6.1": "RBAC: roles & the permission seam",
    "6.2": "File storage",
    "6.3": "Data protection: signed URLs & secrets at rest",
    "6.4": "The SSRF seam",
    "6.5": "MFA / TOTP step-up",
    "7.1": "GDPR: export & erasure",
    "7.2": "In-app notifications",
    "7.3": "Public API & API keys",
    "7.4": "Outbound webhooks",
    "7.5": "Admin back-office & impersonation",
    "8.1": "Single-origin hosting",
    "8.2": "Container & staging",
    "8.3": "The deploy pipeline & CI gates",
    "8.4": "The RLS tenancy backstop",
    "9.1": "Make it yours (rebrand & de-sample)",
    "A.1": "Appendix — MAUI shells & parity",
    "A.2": "Appendix — native auth bridge",
}

# Non-lesson buckets: files a learner does NOT hand-type, with the reason.
BUCKETS: dict[str, str] = {
    "GEN": "Generated by tooling in the lesson noted (dotnet ef / dotnet restore) — never hand-typed",
    "VENDORED": "Third-party asset shipped by a template/package — copied, not written",
    "META": "Repo meta / docs / authoring tooling — not part of the rebuilt app",
}

# ---------------------------------------------------------------------------
# Ordered mapping rules — FIRST MATCH WINS. (pattern, lesson-or-bucket, note)
# Exact paths precede globs so specific files can override folder defaults.
# ---------------------------------------------------------------------------
RULES: list[tuple[str, str, str]] = [
    # ---- generated / vendored / meta ----
    ("src/Infrastructure/Persistence/Migrations/*", "GEN", "dotnet ef migrations add — in the lesson that adds each entity"),
    ("*/packages.lock.json", "GEN", "dotnet restore --locked-mode (lesson 1.1)"),
    ("src/Maui/wwwroot/lib/*", "VENDORED", "Blazor template's bundled Bootstrap"),
    ("src/Maui/Resources/*", "VENDORED", "MAUI template assets (icon/splash/fonts) — replaced in 9.1"),
    ("docs/DEPLOYMENT.md", "8.2", "the runbook is a taught artifact — the learner writes their own"),
    ("docs/QA_TEST_PLAN.md", "8.3", "release readiness: manual QA plan beside the automated gates"),
    (".github/pull_request_template.md", "1.6", "the PR checklist — process as a gate"),
    ("docs/brand/*", "9.1", "brand asset masters (web/store icons) — regenerated with the learner's brand"),
    ("docs/*", "META", "authoring docs; the course TEACHES writing these in 0.1"),
    ("*.md", "META", "docs"),
    ("*.py", "META", "authoring tooling"),
    ("*.pdf", "META", "generated QA guides"),
    (".claude/*", "META", "assistant config"),

    # ---- Part 0 ----
    (".gitignore", "0.2", ""),
    (".gitattributes", "0.2", ""),
    (".gitleaks.toml", "0.2", "secret-scanning gate — part of 'secrets never in the repo'"),
    (".env.example", "0.2", "documented env contract (ADR-001); grows every config lesson"),
    ("docker-compose.yml", "0.2", "Postgres 17 + Mailpit; grows in 2.3/8.2"),

    # ---- Part 1 ----
    ("Perezosoft.slnx", "1.1", ""),
    ("Directory.Build.props", "1.1", "warnings-as-errors etc."),
    ("Directory.Packages.props", "1.1", "Central Package Management (R25/R27)"),
    (".config/dotnet-tools.json", "1.1", "committed CI tool-version manifest (v3 T51/R63)"),
    ("tests/Api.Tests/DataProtectionIdentityTests.cs", "6.5", "DataProtection purposes frozen — a rename orphans every protected payload (v3 TR-8)"),
    ("tests/Api.Tests/EnforcementGateTests.cs", "1.4", "SDK-pin agreement, host index.html parity, doc-map/QA-count sync (v3 T60: R61/R68/R75)"),
    ("*/Perezosoft.*.csproj", "1.1", "created here; PackageReferences added as lessons need them"),
    ("src/Api/Properties/launchSettings.json", "1.1", ""),
    ("src/Maui/Properties/launchSettings.json", "A.1", ""),
    ("src/Api/appsettings*.json", "1.4", "non-secret config; grows every config lesson"),
    ("src/Api/Perezosoft.Api.http", "1.2", "REST client scratchpad — grows with each endpoint"),
    ("src/Api/Program.cs", "1.2", "born here; every part adds registrations/middleware"),
    ("tests/Api.Tests/HarnessSmokeTests.cs", "1.2", ""),
    ("tests/Api.Tests/Integration/HarnessSmokeTests.cs", "1.2", ""),
    ("tests/Api.Tests/Infrastructure/IntegrationTestFactory.cs", "1.2", ""),
    ("tests/Api.Tests/Infrastructure/FakeHostEnvironment.cs", "1.2", ""),
    ("src/Infrastructure/Persistence/AppDbContext.cs", "1.3", "born here; filter added 2.6, interceptors 2.7/4.6, DbSets throughout"),
    ("src/Api/AppDbContextFactory.cs", "1.3", "design-time factory for dotnet ef"),
    ("tests/Api.Tests/AppDbContextFactoryTests.cs", "1.3", ""),
    ("tests/Api.Tests/Infrastructure/PostgresFixture.cs", "1.3", ""),
    ("tests/Api.Tests/Infrastructure/PostgresTestBase.cs", "1.3", "model-derived TRUNCATE (R11)"),
    ("tests/Api.Tests/Infrastructure/ServiceHarness.cs", "1.3", ""),
    ("tests/Api.Tests/Infrastructure/TestAppDbContext.cs", "1.3", "test-only subclass so platform tests don't depend on Notes (R9)"),
    ("tests/Api.Tests/MigrationsTests.cs", "1.3", ""),
    ("src/Api/Configuration/SettingsProvider.cs", "1.4", ""),
    ("src/Api/Configuration/SettingsRegistration.cs", "1.4", "the one blessed Bind+ValidateOnStart pattern (R22)"),
    ("src/Api/Configuration/ServiceRegistrationExtensions.cs", "1.4", "grows as services appear"),
    ("src/Infrastructure/ServiceCollectionExtensions.cs", "1.4", "grows as infra appears"),
    ("tests/Api.Tests/DocAndConfigSyncTests.cs", "1.4", "config keys must exist in .env.example + appsettings (R20)"),
    ("src/Api/Services/ErrorResponse.cs", "1.5", "shared envelope; never ex.Message (R16/R18)"),

    # ---- Part 2 ----
    ("src/Core/Entities/User.cs", "2.1", ""),
    ("src/Infrastructure/Persistence/Configurations/UserConfiguration.cs", "2.1", ""),
    ("src/Core/Repositories/IUserRepository.cs", "2.1", ""),
    ("src/Infrastructure/Repositories/UserRepository.cs", "2.1", ""),
    ("src/Api/Services/UserService.cs", "2.1", ""),
    ("tests/Api.Tests/UserServiceTests.cs", "2.1", ""),
    ("src/Api/Services/JwtTokenService.cs", "2.1", ""),
    ("src/Api/Services/JwtClaims.cs", "2.1", ""),
    ("src/Api/Configuration/IJwtSettings.cs", "2.1", ""),
    ("src/Api/Configuration/JwtValidation.cs", "2.1", ""),
    ("src/Api/Services/ITokenGenerator.cs", "2.1", ""),
    ("src/Api/Services/TokenGenerator.cs", "2.1", ""),
    ("src/Api/Services/ITokenHasher.cs", "2.1", ""),
    ("src/Api/Services/TokenHasher.cs", "2.1", "store hashes, never raw tokens"),
    ("tests/Api.Tests/TokenServiceTests.cs", "2.1", ""),
    ("tests/Api.Tests/TokenHasherTests.cs", "2.1", "hasher hostile-input + fixed-time contract (v3 TB-AUTH-8)"),
    ("tests/Api.Tests/Integration/RefreshReplayTests.cs", "2.1", "rotated-token replay revokes all sessions (v3 TB-AUTH-1)"),
    ("src/Api/Controllers/AuthControllerBase.cs", "2.1", ""),
    ("src/Api/Controllers/AuthController.cs", "2.1", "grows through 2.4/2.5/6.5"),
    ("src/Api/Models/AuthModels.cs", "2.1", ""),
    ("src/Api/Models/TokenResponse.cs", "2.1", ""),
    ("src/Api/Models/UserProfileResponse.cs", "2.1", ""),
    ("src/Api/Authentication/ClaimsPrincipalExtensions.cs", "2.1", ""),
    ("src/Core/Entities/RefreshToken.cs", "2.2", ""),
    ("src/Infrastructure/Persistence/Configurations/RefreshTokenConfiguration.cs", "2.2", ""),
    ("src/Core/Repositories/IRefreshTokenRepository.cs", "2.2", ""),
    ("src/Infrastructure/Repositories/RefreshTokenRepository.cs", "2.2", ""),
    ("src/Api/Services/RefreshTokenService.cs", "2.2", "rotation + reuse detection"),
    ("src/Api/Services/SessionService.cs", "2.2", ""),
    ("tests/Api.Tests/SessionServiceTests.cs", "2.2", ""),
    ("src/Api/Services/ICookieService.cs", "2.2", ""),
    ("src/Api/Services/CookieService.cs", "2.2", "refresh cookie: HttpOnly/SameSite decisions"),
    ("tests/Api.Tests/CookieServiceTests.cs", "2.2", ""),
    ("src/Core/Abstractions/IEmailSender.cs", "2.3", "the ONLY way to send email"),
    ("src/Infrastructure/Email/SmtpEmailSender.cs", "2.3", "MailKit quarantined here"),
    ("src/Infrastructure/Email/SmtpSettings.cs", "2.3", ""),
    ("tests/Api.Tests/SmtpSettingsTests.cs", "2.3", "incl. the SMTP-revocation knob (PR #125)"),
    ("src/Infrastructure/Email/BrandedEmail.cs", "2.3", "inline-branded templates — the rebrand trap"),
    ("src/Infrastructure/Email/EmailStrings.resx", "2.3", "localized in 3.5"),
    ("src/Infrastructure/Email/EmailStrings.es.resx", "3.5", ""),
    ("src/Infrastructure/Email/Assets/logo.png", "2.3", ""),
    ("src/Core/Entities/LoginToken.cs", "2.4", ""),
    ("src/Infrastructure/Persistence/Configurations/LoginTokenConfiguration.cs", "2.4", ""),
    ("src/Core/Repositories/ILoginTokenRepository.cs", "2.4", ""),
    ("src/Infrastructure/Repositories/LoginTokenRepository.cs", "2.4", ""),
    ("src/Api/Services/PasswordlessService.cs", "2.4", "single-use, hashed, time-limited"),
    ("tests/Api.Tests/PasswordlessServiceTests.cs", "2.4", ""),
    ("tests/Core.Tests/LoginTokenTests.cs", "2.4", ""),
    ("tests/Core.Tests/Auth/NativeOtpLockoutTests.cs", "2.4", "OTP resend-proof lockout coverage on the native verify path (landed on develop post-write)"),
    ("tests/Api.Tests/OtpErrorMappingTests.cs", "2.4", ""),
    ("src/Api/Services/SingleUseCacheToken.cs", "2.4", "one-shot handoff token"),
    ("tests/Api.Tests/SingleUseCacheTokenTests.cs", "2.4", ""),
    ("src/Api/Services/AuthProviders.cs", "2.5", "'new provider = one line'"),
    ("src/Api/Services/IClaimsExtractor.cs", "2.5", ""),
    ("src/Api/Services/ClaimsExtractor.cs", "2.5", "fail-closed normalization (R17)"),
    ("tests/Api.Tests/ClaimsExtractorTests.cs", "2.5", ""),
    ("src/Api/Services/ProviderEmailTrust.cs", "2.5", "account-takeover guard"),
    ("tests/Api.Tests/ProviderEmailTrustTests.cs", "2.5", ""),
    ("src/Api/Services/LinkTokenService.cs", "2.5", ""),
    ("src/Core/Entities/UserLogin.cs", "2.5", ""),
    ("src/Infrastructure/Persistence/Configurations/UserLoginConfiguration.cs", "2.5", ""),
    ("src/Core/Repositories/IUserLoginRepository.cs", "2.5", ""),
    ("src/Infrastructure/Repositories/UserLoginRepository.cs", "2.5", ""),
    ("src/Core/Entities/ITenantScoped.cs", "2.6", "the marker the filter keys off"),
    ("src/Core/Abstractions/ICurrentTenant.cs", "2.6", ""),
    ("src/Api/Services/HttpCurrentTenant.cs", "2.6", "tenant_id claim -> request scope"),
    ("tests/Api.Tests/HttpCurrentTenantTests.cs", "2.6", ""),
    ("tests/Api.Tests/TenantScopeFilterTests.cs", "2.6", "the leak-then-fix test"),
    ("tests/Api.Tests/TenantInvariantTests.cs", "2.6", "every ITenantScoped entity filtered or allowlisted (R2)"),
    ("src/Infrastructure/Persistence/TenantStampingInterceptor.cs", "2.7", "write-side isolation"),
    ("tests/Api.Tests/TenantStampingInterceptorTests.cs", "2.7", ""),
    ("src/Core/Abstractions/ITenantContext.cs", "2.7", "EnterTenant for system-auth writes"),
    ("tests/Api.Tests/EnterTenantScopingTests.cs", "2.7", ""),
    ("src/Core/Entities/Tenant.cs", "2.8", ""),
    ("src/Core/Entities/TenantMembership.cs", "2.8", ""),
    ("src/Infrastructure/Persistence/Configurations/TenantConfiguration.cs", "2.8", ""),
    ("src/Infrastructure/Persistence/Configurations/TenantMembershipConfiguration.cs", "2.8", ""),
    ("src/Core/Repositories/ITenantRepository.cs", "2.8", ""),
    ("src/Infrastructure/Repositories/TenantRepository.cs", "2.8", ""),
    ("src/Api/Services/TenantService.cs", "2.8", ""),
    ("src/Api/Models/TenantModels.cs", "2.8", ""),
    ("src/Api/Controllers/HouseholdController.cs", "2.8", "app-facing tenant surface"),
    ("src/Core/Entities/TenantInvitation.cs", "2.9", ""),
    ("src/Infrastructure/Persistence/Configurations/TenantInvitationConfiguration.cs", "2.9", ""),
    ("src/Core/Repositories/ITenantInvitationRepository.cs", "2.9", ""),
    ("src/Infrastructure/Repositories/TenantInvitationRepository.cs", "2.9", ""),
    ("src/Api/Services/TenantInvitationService.cs", "2.9", ""),
    ("tests/Core.Tests/TenantInvitationTests.cs", "2.9", ""),
    ("src/Api/Controllers/HouseholdInvitationsController.cs", "2.9", ""),
    ("src/Api/Services/TenantDissolutionService.cs", "2.9", "contributor fan-out"),
    ("src/Core/Abstractions/ITenantDataContributor.cs", "2.9", "the seam GDPR later extends"),
    ("tests/Api.Tests/WipeDataTests.cs", "2.9", ""),

    # ---- Part 3 ----
    ("src/Core/Repositories/IRepository.cs", "3.1", "tenant-scoped Query() + QueryAllTenants escape hatch"),
    ("src/Core/Repositories/IUnitOfWork.cs", "3.1", ""),
    ("src/Infrastructure/Repositories/EfRepository.cs", "3.1", ""),
    ("src/Infrastructure/Repositories/EfUnitOfWork.cs", "3.1", ""),
    ("tests/Api.Tests/RepositoryScopingTests.cs", "3.1", ""),
    ("src/Api/Features/Notes/*", "3.2", "the reference slice — deleted in 9.1"),
    ("src/Core/Entities/Note.cs", "3.2", ""),
    ("src/Infrastructure/Persistence/Configurations/NoteConfiguration.cs", "3.2", ""),
    ("src/Api/Endpoints/FeatureEndpointExtensions.cs", "3.2", "MapTenantFeatureGroup (R6)"),
    ("src/Api/Configuration/AuthPolicies.cs", "3.2", ""),
    ("tests/Api.Tests/NotesSliceTests.cs", "3.2", ""),
    ("tests/Api.Tests/FeatureAuthorizationTests.cs", "3.2", ""),
    ("tests/Api.Tests/ArchitectureTests.cs", "3.3", "born here; gains a rule per part (R5/R6/R15…)"),
    ("tests/Ui.Tests/*", "3.4", "bUnit component-test chassis for the RCL (v3 TOOL-2) — doubles + one proving test"),
    ("src/Web/Program.cs", "3.4", ""),
    ("src/Web/_Imports.razor", "3.4", ""),
    ("src/Web/Http/AuthHeaderHandler.cs", "3.4", ""),
    ("src/Web/Http/CookieHandler.cs", "3.4", ""),
    ("src/Web/Http/CookieSessionStore.cs", "3.4", ""),
    ("src/Web/appsettings*.json", "3.4", ""),
    ("src/Web/wwwroot/*", "3.4", ""),
    ("src/Shared.Ui/App.razor", "3.4", ""),
    ("src/Shared.Ui/_Imports.razor", "3.4", ""),
    ("src/Shared.Ui/Layout/MainLayout.razor", "3.4", ""),
    ("src/Shared.Ui/Components/AppHeader.razor", "3.4", ""),
    ("src/Shared.Ui/Pages/Home.razor", "3.4", ""),
    ("src/Shared.Ui/Pages/Login.razor", "3.4", ""),
    ("src/Shared.Ui/Pages/AuthCallback.razor", "3.4", ""),
    ("src/Shared.Ui/Pages/AuthError.razor", "3.4", ""),
    ("src/Shared.Ui/Pages/Join.razor", "3.4", "invitation accept UI (pairs with 2.9)"),
    ("src/Shared.Ui/Auth/AuthService.cs", "3.4", ""),
    ("src/Shared.Ui/Auth/AuthErrorCopy.cs", "3.4", "server error code -> localized copy key; keeps 2.4's enumeration-safe collapse client-side (landed on develop post-write)"),
    ("src/Shared.Ui/Auth/ISessionStore.cs", "3.4", "per-platform session seam"),
    ("src/Shared.Ui/Auth/IOAuthInitiator.cs", "3.4", ""),
    ("src/Shared.Ui/Auth/AppClaims.cs", "3.4", ""),
    ("src/Shared.Ui/JsConfirm.cs", "3.4", ""),
    ("src/Shared.Ui/Resources/AppStrings.cs", "3.5", ""),
    ("src/Shared.Ui/Resources/AppStrings.resx", "3.5", ""),
    ("src/Shared.Ui/Resources/AppStrings.es.resx", "3.5", ""),
    ("src/Shared.Ui/Components/LanguageSwitcher.razor", "3.5", ""),
    ("tests/E2E.Tests/I18nTests.cs", "3.5", ""),
    ("tests/Api.Tests/ResourceParityTests.cs", "3.5", "EN/ES resx key parity — no untranslated or orphan keys (2026-07 truth-up)"),
    ("tests/E2E.Tests/LocaleMismatchJoinTests.cs", "3.5", "locale-mismatch reload preserves /join (v3 TB-UI-16, UX-1 end-to-end)"),
    ("tests/E2E.Tests/E2ETestBase.cs", "3.6", ""),
    ("tests/E2E.Tests/Mailpit.cs", "3.6", "read OTPs from the fake inbox"),
    ("tests/E2E.Tests/Pages/*", "3.6", "Page Object Model"),
    ("tests/E2E.Tests/AuthFlowTests.cs", "3.6", ""),

    # ---- Part 4 ----
    ("src/Core/Abstractions/IOutbox.cs", "4.1", ""),
    ("src/Core/Abstractions/IOutboxHandler.cs", "4.1", ""),
    ("src/Core/Entities/OutboxMessage.cs", "4.1", ""),
    ("src/Infrastructure/Persistence/Configurations/OutboxMessageConfiguration.cs", "4.1", ""),
    ("src/Infrastructure/Outbox/*", "4.1", "dispatcher + SKIP LOCKED claiming"),
    ("tests/Api.Tests/Outbox/OutboxProcessorTests.cs", "4.1", ""),
    ("src/Infrastructure/Email/OutboxEmailSender.cs", "4.2", "decorator: same seam, now crash-safe"),
    ("src/Infrastructure/Email/EmailOutboxHandler.cs", "4.2", ""),
    ("tests/Api.Tests/Outbox/OutboxEmailTests.cs", "4.2", ""),
    ("src/Core/Abstractions/IInbox.cs", "4.3", ""),
    ("src/Core/Entities/InboxMessage.cs", "4.3", ""),
    ("src/Infrastructure/Persistence/Configurations/InboxMessageConfiguration.cs", "4.3", ""),
    ("src/Infrastructure/Inbox/EfInbox.cs", "4.3", "dedup on (Source, IdempotencyKey)"),
    ("tests/Api.Tests/Inbox/InboxTests.cs", "4.3", ""),
    ("src/Core/Abstractions/IScheduledJob.cs", "4.4", ""),
    ("src/Infrastructure/Scheduling/*", "4.4", ""),
    ("tests/Api.Tests/Scheduling/*", "4.4", ""),
    ("src/Api/Observability/*", "4.5", ""),
    ("tests/Api.Tests/Observability/*", "4.5", ""),
    ("src/Core/Abstractions/IAuditLog.cs", "4.6", ""),
    ("src/Core/Entities/AuditEvent.cs", "4.6", ""),
    ("src/Infrastructure/Persistence/Configurations/AuditEventConfiguration.cs", "4.6", ""),
    ("src/Infrastructure/Audit/AuditLog.cs", "4.6", ""),
    ("src/Infrastructure/Audit/AuditDataContributor.cs", "4.6", ""),
    ("src/Infrastructure/Persistence/AuditAppendOnlyInterceptor.cs", "4.6", "append-only enforced structurally"),
    ("tests/Api.Tests/AuditLogTests.cs", "4.6", ""),

    # ---- Part 5 ----
    ("src/Core/Abstractions/IBillingProvider.cs", "5.1", ""),
    ("src/Core/Billing/PlanCatalog.cs", "5.1", ""),
    ("src/Core/Entities/Subscription.cs", "5.1", "projection, not source of truth"),
    ("src/Infrastructure/Persistence/Configurations/SubscriptionConfiguration.cs", "5.1", ""),
    ("src/Core/Abstractions/IEntitlementService.cs", "5.1", ""),
    ("src/Api/Services/EntitlementService.cs", "5.1", ""),
    ("src/Api/Endpoints/EntitlementEndpointExtensions.cs", "5.1", "RequireEntitlement -> 402"),
    ("src/Infrastructure/Billing/FakeBillingProvider.cs", "5.1", "throws outside Development (R1)"),
    ("src/Api/Services/BillingService.cs", "5.1", ""),
    ("src/Api/Controllers/BillingController.cs", "5.1", ""),
    ("src/Api/Models/BillingModels.cs", "5.1", ""),
    ("tests/Api.Tests/Billing/EntitlementServiceTests.cs", "5.1", ""),
    ("tests/Api.Tests/Billing/RequireEntitlementFilterTests.cs", "5.1", ""),
    ("tests/Api.Tests/Billing/BillingProviderRegistrationTests.cs", "5.1", ""),
    ("tests/Api.Tests/Billing/BillingServiceTests.cs", "5.1", ""),
    ("tests/Api.Tests/Billing/BillingControllerTests.cs", "5.1", ""),
    ("tests/Api.Tests/Billing/SubscriptionTenantIsolationTests.cs", "5.1", ""),
    ("src/Infrastructure/Billing/StripeBillingProvider.cs", "5.2", ""),
    ("src/Infrastructure/Billing/StripeSettings.cs", "5.2", ""),
    ("src/Api/Controllers/BillingWebhookController.cs", "5.2", "signature-auth entry; EnterTenant"),
    ("src/Api/Services/BillingWebhookHandler.cs", "5.2", "inbox dedup + strictly-newer projection (R29)"),
    ("tests/Api.Tests/Billing/StripeBillingProviderTests.cs", "5.2", ""),
    ("tests/Api.Tests/Billing/BillingWebhookControllerTests.cs", "5.2", ""),
    ("tests/Api.Tests/Billing/BillingWebhookHandlerTests.cs", "5.2", ""),
    ("src/Core/Abstractions/IQuotaService.cs", "5.3", ""),
    ("src/Api/Services/QuotaService.cs", "5.3", "atomic under concurrency (R30)"),
    ("src/Core/Entities/UsageCounter.cs", "5.3", ""),
    ("src/Infrastructure/Persistence/Configurations/UsageCounterConfiguration.cs", "5.3", ""),
    ("src/Api/Services/BillingNotifier.cs", "5.3", ""),
    ("src/Api/Services/SubscriptionLapseSweepJob.cs", "5.3", ""),
    ("src/Api/Services/BillingDataContributor.cs", "5.3", ""),
    ("src/Infrastructure/Billing/BillingCancelOutboxHandler.cs", "5.3", ""),
    ("tests/Api.Tests/Billing/QuotaServiceTests.cs", "5.3", ""),
    ("tests/Api.Tests/Billing/SubscriptionLapseSweepJobTests.cs", "5.3", ""),
    ("tests/Api.Tests/Billing/BillingDissolveTests.cs", "5.3", ""),

    # ---- Part 6 ----
    ("src/Core/Authorization/Permission.cs", "6.1", ""),
    ("src/Core/Authorization/RolePermissions.cs", "6.1", "matrix: coarse capabilities, not ACLs"),
    ("src/Core/Abstractions/IPermissionService.cs", "6.1", ""),
    ("src/Api/Services/PermissionService.cs", "6.1", ""),
    ("src/Api/Endpoints/PermissionEndpointExtensions.cs", "6.1", "RequirePermission -> 403"),
    ("src/Api/Authentication/RequireTenantPermissionAttribute.cs", "6.1", ""),
    ("src/Api/Controllers/TenantApiControllerBase.cs", "6.1", "controllers inherit the gate (R4)"),
    ("src/Shared.Ui/Pages/Household.razor", "6.1", "admin-aware roster UI"),
    ("tests/Core.Tests/RolePermissionsTests.cs", "6.1", ""),
    ("tests/Api.Tests/Rbac/*", "6.1", ""),
    ("tests/Api.Tests/Integration/RbacForbiddenIntegrationTests.cs", "6.1", ""),
    ("src/Core/Abstractions/IFileStorage.cs", "6.2", ""),
    ("src/Infrastructure/Files/LocalDiskFileStorage.cs", "6.2", ""),
    ("src/Infrastructure/Files/LocalFileStorageSettings.cs", "6.2", ""),
    ("src/Infrastructure/Files/S3FileStorage.cs", "6.2", ""),
    ("src/Infrastructure/Files/S3StorageSettings.cs", "6.2", ""),
    ("src/Infrastructure/Files/StorageKeys.cs", "6.2", "tenant-scoped keys"),
    ("tests/Api.Tests/Files/LocalDiskFileStorageTests.cs", "6.2", ""),
    ("tests/Api.Tests/Files/S3FileStorageMinioTests.cs", "6.2", ""),
    ("tests/Api.Tests/Files/FileStorageRegistrationTests.cs", "6.2", ""),
    ("src/Infrastructure/Files/FileDownloadTokenizer.cs", "6.3", "DataProtection-signed URLs"),
    ("src/Api/Controllers/FilesController.cs", "6.3", ""),
    ("tests/Api.Tests/Files/FileDownloadTokenizerTests.cs", "6.3", ""),
    ("tests/Api.Tests/Files/FilesControllerTests.cs", "6.3", ""),
    ("src/Core/Abstractions/IOutboundUrlGuard.cs", "6.4", ""),
    ("src/Infrastructure/Http/OutboundUrlGuard.cs", "6.4", "SSRF: block loopback/RFC-1918/metadata (R3)"),
    ("tests/Api.Tests/Webhooks/OutboundUrlGuardTests.cs", "6.4", ""),
    ("tests/Api.Tests/Infrastructure/AllowAllUrlGuard.cs", "6.4", "test-only bypass"),
    ("src/Core/Entities/UserMfa.cs", "6.5", "secret encrypted at rest"),
    ("src/Core/Entities/MfaRecoveryCode.cs", "6.5", "hashed, single-use"),
    ("src/Infrastructure/Persistence/Configurations/UserMfaConfiguration.cs", "6.5", ""),
    ("src/Infrastructure/Persistence/Configurations/MfaRecoveryCodeConfiguration.cs", "6.5", ""),
    ("src/Api/Services/MfaService.cs", "6.5", ""),
    ("src/Api/Services/MfaChallengeService.cs", "6.5", ""),
    ("src/Api/Services/MfaLoginService.cs", "6.5", ""),
    ("src/Api/Controllers/MfaController.cs", "6.5", ""),
    ("src/Api/Models/MfaModels.cs", "6.5", ""),
    ("src/Api/Services/MfaUserDataContributor.cs", "6.5", ""),
    ("src/Shared.Ui/Components/MfaCard.razor", "6.5", ""),
    ("src/Shared.Ui/Pages/Settings.razor", "6.5", ""),
    ("tests/Api.Tests/Mfa/*", "6.5", ""),
    ("tests/Api.Tests/Integration/MfaStepUpIntegrationTests.cs", "6.5", "step-up on EVERY sign-in path"),
    ("tests/E2E.Tests/MfaJourneyTests.cs", "6.5", ""),
    ("tests/E2E.Tests/Totp.cs", "6.5", ""),

    # ---- Part 7 ----
    ("src/Core/Abstractions/IUserDataContributor.cs", "7.1", "per-user erasure seam (R12)"),
    ("src/Api/Services/TenantExportService.cs", "7.1", ""),
    ("src/Api/Services/AccountErasureService.cs", "7.1", ""),
    ("src/Api/Controllers/AccountController.cs", "7.1", ""),
    ("tests/Api.Tests/Gdpr/*", "7.1", ""),
    ("src/Core/Entities/Notification.cs", "7.2", ""),
    ("src/Core/Entities/NotificationPreference.cs", "7.2", "per-USER prefs — the sanctioned exception"),
    ("src/Infrastructure/Persistence/Configurations/NotificationConfiguration.cs", "7.2", ""),
    ("src/Infrastructure/Persistence/Configurations/NotificationPreferenceConfiguration.cs", "7.2", ""),
    ("src/Api/Services/NotificationService.cs", "7.2", ""),
    ("src/Api/Services/NotificationUserDataContributor.cs", "7.2", ""),
    ("src/Api/Controllers/NotificationsController.cs", "7.2", ""),
    ("tests/Api.Tests/Integration/NotificationClearScopeTests.cs", "7.2", "bulk-clear requires an explicit scope (v3 LB-UI-10)"),
    ("tests/Api.Tests/Integration/ContributorRegistrationTests.cs", "6.3", "every declared contributor resolves from the app DI (v3 TB-TEN-11)"),
    ("tests/Api.Tests/Integration/PostmanParityTests.cs", "8.3", "every mapped /api endpoint documented in the canonical collection (v3 TR-6)"),
    ("src/Api/Models/NotificationModels.cs", "7.2", ""),
    ("src/Shared.Ui/Components/NotificationBell.razor", "7.2", ""),
    ("src/Shared.Ui/Components/NotificationPrefsCard.razor", "7.2", ""),
    ("tests/Api.Tests/Notify/*", "7.2", ""),
    ("src/Core/Entities/ApiKey.cs", "7.3", "hash-only storage"),
    ("src/Infrastructure/Persistence/Configurations/ApiKeyConfiguration.cs", "7.3", ""),
    ("src/Api/Services/ApiKeyService.cs", "7.3", ""),
    ("src/Api/Authentication/ApiKeyAuthenticationHandler.cs", "7.3", "key -> tenant-scoped principal"),
    ("src/Api/Endpoints/ApiKeyEndpoints.cs", "7.3", ""),
    ("src/Api/Configuration/PublicApiSettings.cs", "7.3", "config-gated default-OFF (R21)"),
    ("src/Api/Configuration/RateLimiting.cs", "7.3", ""),
    ("tests/Api.Tests/PublicApi/*", "7.3", ""),
    ("tests/Api.Tests/RateLimitingTests.cs", "7.3", ""),
    ("src/Core/Entities/WebhookSubscription.cs", "7.4", ""),
    ("src/Core/Entities/WebhookDelivery.cs", "7.4", ""),
    ("src/Infrastructure/Persistence/Configurations/WebhookSubscriptionConfiguration.cs", "7.4", ""),
    ("src/Infrastructure/Persistence/Configurations/WebhookDeliveryConfiguration.cs", "7.4", ""),
    ("src/Core/Webhooks/WebhookSignature.cs", "7.4", "HMAC signing"),
    ("tests/Core.Tests/WebhookSignatureTests.cs", "7.4", ""),
    ("src/Api/Services/WebhookService.cs", "7.4", ""),
    ("src/Api/Endpoints/WebhookEndpoints.cs", "7.4", ""),
    ("src/Infrastructure/Webhooks/WebhookOutboxHandler.cs", "7.4", ""),
    ("src/Infrastructure/Webhooks/WebhookSender.cs", "7.4", ""),
    ("src/Infrastructure/Webhooks/WebhookSecretProtector.cs", "7.4", "encrypted at rest (builds on 6.3)"),
    ("src/Api/Configuration/WebhooksSettings.cs", "7.4", ""),
    ("tests/Api.Tests/Webhooks/WebhookDeliveryTests.cs", "7.4", ""),
    ("tests/Api.Tests/Webhooks/WebhookDeliveryLogTests.cs", "7.4", ""),
    ("tests/Api.Tests/Webhooks/WebhookSubscriptionServiceTests.cs", "7.4", ""),
    ("src/Api/Configuration/PlatformAdminSettings.cs", "7.5", ""),
    ("src/Api/Services/PlatformStaffService.cs", "7.5", ""),
    ("src/Api/Controllers/AdminApiControllerBase.cs", "7.5", ""),
    ("src/Api/Controllers/AdminController.cs", "7.5", "sanctioned QueryAllTenants + audited EnterTenant"),
    ("src/Api/Services/AdminBroadcastOutboxHandler.cs", "7.5", "announce-all -> outbox fan-out to every user"),
    ("src/Api/Models/AdminModels.cs", "7.5", ""),
    ("src/Shared.Ui/Pages/AdminConsole.razor", "7.5", ""),
    ("tests/Api.Tests/Admin/*", "7.5", ""),
    ("tests/Core.Tests/Auth/ImpersonationIdentityTests.cs", "7.5", "client identity swap raises AuthService.IdentityChanged so the header re-sources on impersonate"),

    # ---- Part 8 ----
    ("src/Api/Configuration/ProxyForwardingExtensions.cs", "8.1", "config-gated forwarded headers"),
    ("tests/Api.Tests/Hosting/*", "8.1", ""),
    ("tests/Api.Tests/Infrastructure/TempWebRoot.cs", "8.1", ""),
    ("tests/Api.Tests/Integration/SingleOriginHostingTests.cs", "8.1", ""),
    ("Dockerfile", "8.2", "DEPLOY-2"),
    (".dockerignore", "8.2", ""),
    (".github/workflows/ci.yml", "1.6", "born here (build+test+secret/license gates); every part adds jobs — e2e 3.6, docker 8.2, deploy 8.3, native A.1"),
    (".github/forbidden-licenses.json", "1.6", "copyleft ban (R26)"),
    (".github/*", "8.3", ""),

    ("render.yaml", "8.2", "Render blueprint (ADR-017)"),

    # ---- caught by the gate's first run ----
    ("src/Shared.Ui/Components/AppHeader.razor.css", "3.4", "co-located component CSS"),
    ("src/Shared.Ui/Layout/MainLayout.razor.css", "3.4", ""),
    ("src/Shared.Ui/Pages/Home.razor.css", "3.4", ""),
    ("src/Shared.Ui/Pages/Login.razor.css", "3.4", ""),
    ("src/Shared.Ui/wwwroot/brand/*", "3.4", "placeholder brand assets — replaced in 9.1"),
    ("src/Shared.Ui/wwwroot/js/qrcode-generator.min.js", "VENDORED", "QR library for MFA enroll"),
    ("src/Shared.Ui/wwwroot/js/mfa-qr.js", "6.5", "JS interop to render the TOTP QR"),
    ("src/Web/Properties/launchSettings.json", "1.1", ""),
    ("tests/E2E.Tests/playwright.runsettings", "3.6", ""),

    # ---- drift absorbed 2026-07-06 (NATIVE waves 1-2, BILLING-8, E2E expansion, DEPLOY-3) ----
    ("src/Shared.Ui/Pages/Billing.razor", "5.1", "BILLING-8 billing summary page"),
    ("tests/E2E.Tests/BillingJourneyTests.cs", "5.1", "fake-provider upgrade loop"),
    ("tests/E2E.Tests/SeatQuotaJourneyTests.cs", "5.3", "seat-quota 402 UX"),
    ("tests/Api.Tests/Auth/AuthProvidersTests.cs", "2.5", ""),
    ("tests/Api.Tests/Integration/AuthProvidersEndpointTests.cs", "2.5", ""),
    ("tests/E2E.Tests/MagicLinkJourneyTests.cs", "3.6", "happy + single-use"),
    ("tests/E2E.Tests/RosterJourneyTests.cs", "6.1", ""),
    ("tests/E2E.Tests/MembershipLifecycleTests.cs", "6.1", "transfer/leave/dissolve/delete-account journeys"),
    ("tests/E2E.Tests/GdprExportJourneyTests.cs", "7.1", ""),
    ("tests/E2E.Tests/NotificationJourneyTests.cs", "7.2", ""),
    ("tests/E2E.Tests/AnnouncementJourneyTests.cs", "7.5", "ADMIN-3 announce -> NOTIFY fan-out"),
    ("tests/Api.Tests/Integration/VersionEndpointTests.cs", "8.3", "version-gated deploy smoke"),
    ("src/Shared.Ui/wwwroot/css/app.css", "3.4", ""),
    ("src/Shared.Ui/ICulturePersistence.cs", "3.5", "culture bootstrap seam (NATIVE-5); MAUI impl in A.1"),
    ("src/Shared.Ui/LocalStorageCulturePersistence.cs", "3.5", ""),
    ("src/Shared.Ui/IFileDownloadLauncher.cs", "6.3", "download seam (NATIVE-3): web same-tab, native share sheet"),
    ("src/Shared.Ui/BrowserFileDownloadLauncher.cs", "6.3", ""),
    ("src/Shared.Ui/AppResumeNotifier.cs", "A.1", "refresh-on-resume seam (NATIVE-4 G2)"),
    ("tests/E2E.Tests/NativeSmokeTests.cs", "A.1", "NATIVE-7 emulator/WebView2 smoke"),
    ("tests/native-smoke-android/*", "A.1", "Android playwright-core smoke harness"),

    # ---- drift absorbed 2026-07-10 (THEME-1 dark mode) ----
    ("src/Shared.Ui/wwwroot/js/theme.js", "3.4", "THEME-1 pre-paint dark-mode bootstrap (data-bs-theme)"),
    ("src/Shared.Ui/IThemePersistence.cs", "3.4", "theme persistence seam (THEME-1) — one localStorage impl serves web + MAUI"),
    ("src/Shared.Ui/LocalStorageThemePersistence.cs", "3.4", ""),
    ("src/Shared.Ui/Components/ThemeSwitcher.razor", "3.4", ""),
    ("tests/E2E.Tests/ThemeJourneyTests.cs", "3.4", "dark-mode journey (live flip, reload persist, cross-device reconcile)"),

    # ---- drift absorbed 2026-08-31 (QA-SEC-03 bfcache guard) ----
    ("src/Shared.Ui/wwwroot/js/bfcache-guard.js", "3.4", "reload bfcache restores — Back after sign-out can't show a stale authenticated view (QA-SEC-03)"),
    ("tests/Api.Tests/BfcacheGuardTests.cs", "3.4", "pins the guard's contract + presence in BOTH hosts' index.html"),

    # ---- drift absorbed 2026-07-14 (PREFS-1 / ADR-022 + BILLING-9) ----
    ("tests/Api.Tests/Billing/AcceptSeatQuotaTests.cs", "5.3", "BILLING-9: seat quota re-checked at invitation ACCEPT (402 seat_limit_reached)"),
    ("tests/Api.Tests/AccountControllerTests.cs", "3.5", "PREFS-1/ADR-022: theme+locale preference-endpoint storage rules"),

    # ---- drift absorbed 2026-07-07 (RLS tenancy backstop, ADR-020 / PR #124) ----
    ("src/Infrastructure/Persistence/RlsDdl.cs", "8.4", "policy DDL — source of the RlsMigrationGateTests parity gate"),
    ("src/Infrastructure/Persistence/RlsSessionInterceptor.cs", "8.4", "sets the tenant GUC per connection"),
    ("src/Infrastructure/Persistence/RlsPostureGuard.cs", "8.4", "gates prod activation (ADR-020)"),
    ("src/Infrastructure/Persistence/RlsTags.cs", "8.4", ""),
    ("docker/db/provision-rls-runtime-role.sql", "8.4", "non-BYPASSRLS runtime role — mirrors prod (Neon) provisioning"),
    ("tests/Api.Tests/Rls/*", "8.4", "backstop + migration-parity + posture-guard tests"),

    # ---- Appendix ----
    ("src/Api/Controllers/NativeAuthController.cs", "A.2", ""),
    ("src/Api/Services/NativeAuthCodeService.cs", "A.2", ""),
    ("src/Api/Services/NativeRedirectPolicy.cs", "A.2", ""),
    ("src/Api/Services/NativeAuthUrls.cs", "A.2", "state CSRF round-trip through login→callback (v3 NAT-9)"),
    ("tests/Api.Tests/NativeAuthCodeServiceTests.cs", "A.2", ""),
    ("tests/Api.Tests/NativeRedirectPolicyTests.cs", "A.2", ""),
    ("tests/Api.Tests/NativeAuthUrlsTests.cs", "A.2", ""),
    ("src/Maui/Auth/*", "A.2", ""),
    ("src/Maui/*", "A.1", ""),
    ("tests/Api.Tests/Infrastructure/TenantPermissionGate.cs", "6.1", "test double for the permission seam"),

    # ---- v3 audit remediation + NATIVE-12 (2026-07) — mapped to the lesson that teaches each seam ----
    ("global.json", "1.1", "single SDK pin source (v3 DEP-4) — pairs with the committed lockfiles"),
    ("tests/Api.Tests/PasswordlessConcurrencyTests.cs", "2.4", "atomic single-use consume + lockout counter (v3 LB-AUTH-2/3)"),
    ("tests/Api.Tests/Architecture/TenantHatchGuard.cs", "2.6", "polices QueryAllTenants call sites (the sanctioned hatch stays reviewable)"),
    ("tests/Api.Tests/Architecture/TenantHatchGuardTests.cs", "2.6", ""),
    ("tests/Api.Tests/Configuration/ConfigPostureTests.cs", "1.4", "pins every config-gated feature CLOSED under empty config (v3 S0-G3)"),
    ("tests/Api.Tests/Architecture/RoutePrefixInspector.cs", "3.3", "route-prefix uniqueness scans MapTenantFeatureGroup too (v3 ADV-P4-1/R100)"),
    ("tests/Api.Tests/Architecture/RoutePrefixInspectorTests.cs", "3.3", ""),
    ("src/Api/Services/UsageCounterDataContributor.cs", "5.3", "quota rows join dissolve/export (v3 LB-TEN-1)"),
    ("src/Api/Services/RecoveryCodeHasher.cs", "6.5", "HKDF-peppered recovery-code hashing (v3 ADM-4)"),
    ("src/Api/Services/ApiKeyDataContributor.cs", "7.3", "hashed keys join dissolve/export (v3 LB-TEN-1)"),
    ("src/Api/Services/WebhookDataContributor.cs", "7.4", "subscriptions + secrets join dissolve/export (v3 LB-TEN-1)"),
    ("src/Core/Abstractions/ICurrentImpersonation.cs", "7.5", "audit rows carry impersonated_by (v3 LB-ADM-1)"),
    ("src/Api/Services/HttpCurrentImpersonation.cs", "7.5", ""),
    ("tests/Api.Tests/Integration/ImpersonationGuardTests.cs", "7.5", "staff gate rejects impersonation tokens (v3 ADM-2)"),
    ("tests/Api.Tests/Architecture/CrossTenantWriteGuard.cs", "8.4", "EnterTenant required on set-based cross-tenant writes — tags don't render for ExecuteUpdate (v3/T7)"),
    ("tests/Api.Tests/Architecture/CrossTenantWriteGuardTests.cs", "8.4", ""),
    ("src/Shared.Ui/Auth/IOAuthResumeStore.cs", "A.2", "OAuth resume-across-process-death seam (NATIVE-12)"),
    ("src/Shared.Ui/Auth/OAuthResumeResult.cs", "A.2", "resume outcome handed to Login/Settings (NATIVE-12)"),
    ("tests/Api.Tests/OAuthResumeTests.cs", "A.2", "marker lifecycle, TTL, MFA handoff, link outcomes (NATIVE-12)"),
]


def classify(path: str) -> tuple[str, str] | None:
    for pattern, lesson, note in RULES:
        if fnmatch(path, pattern):
            return lesson, note
    return None


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    files = subprocess.run(
        ["git", "ls-files"], cwd=root, capture_output=True, text=True, check=True
    ).stdout.splitlines()

    by_lesson: dict[str, list[tuple[str, str]]] = {}
    unmapped: list[str] = []
    for f in files:
        hit = classify(f)
        if hit is None:
            unmapped.append(f)
        else:
            by_lesson.setdefault(hit[0], []).append((f, hit[1]))

    out = ["# Tutorial coverage manifest", "",
           "> Generated by `gen_coverage.py` — do not edit by hand.",
           "> Every tracked file maps to the lesson that builds it, or an explicit",
           "> non-lesson bucket. An unmapped file fails the script (exit 1): that is",
           "> a hole in the course, and the course treats holes the way the repo",
           "> treats arch-rule violations.", ""]

    total_lesson_files = 0
    for lesson_id, title in LESSONS.items():
        entries = by_lesson.get(lesson_id, [])
        if not entries:
            out.append(f"## {lesson_id} — {title}\n\n*(no repo files — narrative/capstone lesson)*\n")
            continue
        total_lesson_files += len(entries)
        out.append(f"## {lesson_id} — {title} ({len(entries)} files)\n")
        for f, note in sorted(entries):
            out.append(f"- `{f}`" + (f" — {note}" if note else ""))
        out.append("")

    for bucket, desc in BUCKETS.items():
        entries = by_lesson.get(bucket, [])
        out.append(f"## [{bucket}] {desc} ({len(entries)} files)\n")
        for f, note in sorted(entries):
            out.append(f"- `{f}`" + (f" — {note}" if note else ""))
        out.append("")

    if unmapped:
        out.append(f"## ❌ UNMAPPED ({len(unmapped)} files) — course holes, fix the rules or add lessons\n")
        for f in sorted(unmapped):
            out.append(f"- `{f}`")
        out.append("")

    out.append(f"**Totals:** {len(files)} tracked files · "
               f"{total_lesson_files} built in lessons · "
               f"{sum(len(by_lesson.get(b, [])) for b in BUCKETS)} bucketed · "
               f"{len(unmapped)} unmapped")

    (root / "docs/tutorial/COVERAGE.md").write_text("\n".join(out) + "\n", encoding="utf-8")

    print(f"{len(files)} files: {total_lesson_files} in lessons, "
          f"{sum(len(by_lesson.get(b, [])) for b in BUCKETS)} bucketed, {len(unmapped)} unmapped")
    if unmapped:
        print("\nUNMAPPED:")
        for f in sorted(unmapped):
            print(f"  {f}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
